$(function(){
				$('form').validate({
					rules:{
						username:{
							required:true,
							rangelength:[3,20]
						},
						password:{
							required:true,
							rangelength:[5,20]
						},
						captcha:{
							required:true
						},
					},
					messages:{
						username:{
							required:'用户名不能为空',
							rangelength:'用户名长度为3-20位'
						},
						password:{
							required:"密码不能为空",
							rangelength:"密码长度为5-20位",
						},
						captcha:{
							required:"验证码不能为空"
						}
					},
					//验证通过执行方法
					unhighlight:function(element,errorClass,validateClass){
						$(element).tooltip('destroy');
					},
					//验证未通过执行方法
					errorPlacement:function(error,element){
						if($(element).next('.tooltip').length>0){
							$(element).attr('data-original-title',error.text()).tooltip('show');
						}else{
							$(element).attr('title',error.text()).tooltip();
						}
					},
					//验证所有验证通过准备提交数据
					submitHandler:function(){
						$('[type="submit"]').button('loading');
						$.post('http://192.168.15.2/gz0820web/login',$('#loginForm').serializeArray(),function(data){
							console.log(data)
								if(data.status!=1){
									$('[type="submit"]').button('reset');
								}else{
									setInterval(function(){
										location.href="777.html";
								},2000);
						}
							$('.modal-body').text(data.msg);
							
							console.log(data.msg)
							$('.modal').modal();
						},'json');
						return false;
					}
				});